#program path
gridss_script = "/installed_tools/scripts/gridss_script.R"
gridss = "/installed_tools/gridss/gridss-1.5.1-jar-with-dependencies.jar"
dbsnp_indel = "/installed_tools/RefGenomes/dbsnp_indel.vcf"
lumpy = "/installed_tools/lumpy-sv/bin/lumpyexpress"
svaba = "/installed_tools/svaba/bin/svaba"
whamg = "/installed_tools/wham/bin/whamg"
manta_config = "/installed_tools/manta/1.3.1/bin/configManta.py"
survivor = "/installed_tools/SURVIVOR/SURVIVOR-1.0.3/Debug/SURVIVOR"
annotsv = "/installed_tools/annotsv/AnnotSV_1.1.1/bin/AnnotSV"
bedtools = "/installed_tools/bedtools/2.26.0/bin/bedtools"
melt = "/installed_tools/MELT/MELTv2.1.5/MELT.jar"
bowtie2 = "/installed_tools/bowtie2/2.2.6/bin/bowtie2"
msisensor = "/installed_tools/msisensor/msisensor"
svviz = "/installed_tools/svviz/svviz1/bin/svviz"
mavis = "/installed_tools/mavis/2.1.1/bin/mavis"
bbtools = "/installed_tools/BBMap/bbmap/reformat.sh"
ontarget = "/installed_tools/scripts/cal_coverage.pl"
tempdir = "/installed_tools/temp/"
gridss_script = "/installed_tools/scripts/gridss_script.R"
dbsnp_indel = "/installed_tools/RefGenomes/dbsnp_indel.vcf"
facets_script = "/installed_tools/scripts/facets_script.R"
sequenza_script = "/installed_tools/scripts/sequenza_script.R"
freec_path = "/installed_tools/scripts/freec.config"
qualimap = "/installed_tools/qualimap/2.2/qualimap"
gatk = "/installed_tools/gatk/3.5/GenomeAnalysisTK.jar"

